### ISSUE TITLE
Pull Manchester out of main HOWL grammar

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/howl#12]
The main HOWL grammar be have something like:

```
EXPRESSION_BLOCK = PREDICATE COLON_ARROWS EXPRESSION EOL
EXPRESSION = #'.+'
```

The `EXPRESSION` itself will match any string, and will be parsed in a second step. We'll plan to support multiple types of expression, with Manchester the default. The code for each type of expression (starting with Manchester) should probably be in its own namespace/file.

See #6 and #10 and the [Design](https://github.com/ontodev/howl/wiki/Design) document.

**Comment by inaimathi** [comment]
Done in https://github.com/ontodev/howl/pull/13
